spring: 
  profiles:
    active: dev

---
server:
  port: 4001
spring:
  profiles: dev
  applications:
    name: employee-manage-system-config-dev

---
server: 
  port: 4002
spring: 
  profiles: prod
  applications:
    name: employee-manage-system-config-prod